apdcl/urls.py
from django.contrib import admin
from django.urls import path,include

admin.site.site_header = "APDCL"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('connections.urls'))
]

connections/urls.py
from django.contrib import admin
from django.urls import path, include
from connections import views

urlpatterns = [
    path('', views.index, name='home'),
    path('index.html', views.index, name='index'),
    path('connection', views.connection, name='connection'),
    path('contact', views.contact, name='contact'),
    path('about', views.about, name='about'),
    path('register', views.register, name='register'),
    path('login', views.userlogin, name='userlogin'),
    path('logout', views.userlogout, name='userlogout'),
    path('form', views.person_create_view, name='person_add'),
    path('<int:pk>/', views.person_update_view, name='person_change'),
    path('ajax/load_division/', views.load_division, name='ajax_load_division'), # AJAX
    path('ajax/load_subdivision/', views.load_subdivision, name='ajax_load_subdivision'),
]

connections/models.py
from django.db import models

# Create your models here.

class Contact(models.Model):
    name = models.CharField(max_length=122)
    email = models.CharField(max_length=122)
    phone = models.IntegerField()
    issue = models.TextField()

    def __str__(self):
        return self.name
    
class connect (models.Model):
    name = models.CharField(max_length=30)
    pincode = models.IntegerField()
    zonetype = models.TextChoices("zonetype","GEC1 GEC2 Rangia Bongaigaon Mangaldai Kokrajhar Barpeta Tezpur Nagaon Morigaon Kanch Cachar Badarpur NLakhimpur Sibsagar Jorhat Golaghat Dibrugarh Tinsukia")
    zone = models.CharField(choices=zonetype.choices, max_length=20,null=True, blank=True)


class Zone (models.Model):
    name = models.CharField(max_length=20,null=True, blank=True)

    def __str__(self):
        return self.name
    
class Division (models.Model):
    zone = models.ForeignKey(Zone,on_delete=models.CASCADE, blank=True)
    name = models.CharField(max_length=20,null=True, blank=True)

    def __str__(self):
        return self.name
    
class SubDivision (models.Model):
    division = models.ForeignKey(Division,on_delete=models.CASCADE, blank=True)
    name = models.CharField(max_length=20,null=True, blank=True)

    def __str__(self):
        return self.name
    
class Consumer(models.Model):
    name = models.CharField(max_length=30,null=True, blank=True)
    address = models.CharField(max_length=100,null=True, blank=True)
    zone = models.ForeignKey(Zone,on_delete=models.CASCADE,null=True, blank=True)
    division= models.ForeignKey(Division,on_delete=models.CASCADE,null=True, blank=True)
    subdivision = models.ForeignKey(SubDivision,on_delete=models.CASCADE,null=True, blank=True)

    def __str__(self):
        return self.name
    

connections/forms.py
from django import forms
from connections.models import Consumer, Zone, Division, SubDivision

class PersonCreationForm(forms.ModelForm):
    class Meta:
        model = Consumer
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['division'].queryset = Division.objects.none()
        self.fields['subdivision'].queryset = SubDivision.objects.none()

        if 'zone' in self.data:
            try:
                zone_id = int(self.data.get('zone'))
                self.fields['division'].queryset = Division.objects.filter(zone_id=zone_id).order_by('name')
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty division queryset

        if 'division' in self.data:
            try:
                division_id = int(self.data.get('division'))
                self.fields['subdivision'].queryset = SubDivision.objects.filter(division_id=division_id).order_by('name')
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty Subdivision queryset

        elif self.instance.pk:
            self.fields['division'].queryset = self.instance.zone.division_set.order_by('name')
            self.fields['subdivision'].queryset = self.instance.division.subdivision_set.order_by('name')

connections/views.py
from django.shortcuts import render,HttpResponse,redirect
from connections.models import connect,Contact
from django.contrib import messages
from django.contrib import auth
from django.contrib.auth.models import User
from django.contrib.auth import login,logout,authenticate
from connections.models import Zone,Division,SubDivision,Consumer

from django.http import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from .forms import PersonCreationForm

# Create your views here.
def index(request):
    return render(request, 'index.html')
def about(request):
    return render(request, 'about.html')

def contact(request):
    if request.method == "POST":
        name = request.POST.get('name')
        email = request.POST.get('email')
        phone = request.POST.get('phone')
        issue = request.POST.get('issue')
        contact = Contact (name = name, email = email, phone = phone, issue = issue)
        contact.save()
        messages.success(request, "Your complaint/query has been sent!")
    return render(request, 'contact.html')

def register(request):
    if request.method == "POST":
        username = request.POST.get('username')
        email = request.POST.get('email')
        password1 = request.POST.get('password1')
        password2 = request.POST.get('password2')

        if password1 == password2:
            if User.objects.filter(email=email).exists():
                messages.info(request,"Email is already in used.")
                return redirect('register')
            elif User.objects.filter(username=username).exists():
                messages.info(request,"Name is already in used.")
                return redirect('register')
            else:
                user = User.objects.create_user(username=username, email=email, password=password1)
                user.save()
                messages.success(request, "Account created successfully!!!")
                return redirect('register')
        else:
            messages.info(request, "Passwords do not match.")
            return redirect('register')
    else:
        #method="GET"  
        return render(request, 'register.html')

def userlogin(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        #check if user has entered correct credentials
        user = auth.authenticate(username=username, password=password)

        if user is not None:
    # A backend authenticated the credentials
            auth.login(request,user)
            messages.success(request,"User logged in successfully!")
            return redirect("index")
        else:
    # No backend authenticated the credentials
            messages.info(request,"User not found! Please enter correct credentials")
            return render(request,'login.html')
    else:
        return render(request, 'login.html')
    
def userlogout(request):
   auth.logout(request)
   return redirect ("/login")

def connection(request):
    return render(request, 'connection.html')
    

def person_create_view(request):
    form = PersonCreationForm()
    if request.method == 'POST':
        form = PersonCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('person_add')
    return render(request, 'form.html', {'form': form})


def person_update_view(request, pk):
    person = get_object_or_404(Consumer, pk=pk)
    form = PersonCreationForm(instance=person)
    if request.method == 'POST':
        form = PersonCreationForm(request.POST, instance=person)
        if form.is_valid():
            form.save()
            return redirect('person_change', pk=pk)
    return render(request, 'form.html', {'form': form})


# AJAX
def load_division(request):
    zone_id = request.GET.get('zone_id')
    divisions = Division.objects.filter(zone_id=zone_id).all()
    return render(request, 'city_dropdown_list_options.html', {'divisions': divisions})

def load_subdivision(request):
    division_id = request.GET.get('division_id')
    subdivisions = SubDivision.objects.filter(division_id=division_id).all()
    return render(request, 'subdivision_dropdown_list_options.html', {'subdivisions': subdivisions})
    # return JsonResponse(list(divisions.values('id', 'name')), safe=False)

templates/about.html
{% extends 'common.html' %}

{% block title %}
About page
{% endblock title %}

{% block body %}

<style>
    .breadcrumb 
    {
      background-color: #f2f2f2;
      padding: 10px;
      border-radius: 5px;
    }
</style>

<nav aria-label="breadcrumb">
    <ol class="breadcrumb py-2">
        <li class="breadcrumb-item">
            <a href="index.html">Home</a>
        </li>
        <li class="breadcrumb-item active" aria-current="page">
            About
        </li>
    </ol>

    <h4><strong>Introduction:</strong> </h4>     
    The Assam State Electricity Board (ASEB) is a State Statutory Body of the state of Assam in India. It is under the
    ownership of Department of Power, Government of Assam. It manages the generation, transmission and distribution of
    electricity in the state of Assam with its divisions Assam Power Generation Corporation Limited, Assam Electricity
    Grid Corporation Limited and Assam Power Distribution Company Limited. </br> </br>

    <h4> <strong>History:</strong> </h4>
    Assam State Electricity Board was established in 1958 in the composite state of Assam under the Electricity Act
    1948. The existing Board was reconstituted in 1975 after the state was trifurcated into Assam, Meghalaya and Mizoram
    in 1972. Two central government entities, North Eastern Electric Power Corporation (NEEPCO) and the Power Grid
    Corporation of India Ltd (PGCIL) supplement the efforts of the state in power development in generation and
    transmission respectively.    </br>  </br>

    <h4> <strong>Goal:</strong>     </h4>  
    The primary purpose of the Company is to undertake distribution, trading and supply of electricity in the state of
    Assam or outside in accordance with provisions of Applicable Law and all activities ancillary or appurtenant
    thereto. It has also the mandate to develop, maintain and operate the power distribution system in the state of
    Assam. In carrying out the work of supplying power, APDCL reaches every part of the state. From Sadiya to Mancachar
    and from Jonai to Lowairpowa. From the hilly areas of North Cachar Hills to the low plains of Morigaon, APDCL is
    expanding its distribution network in spite of many physical hindrances. APDCL is also implementing off-grid solar
    projects in such areas where the distribution network could not reach such as Amarpur area under Chapakhowa
    Sub-division and the 'Char' areas of Brahmaputra river.   </br>

    APDCL is supplying power to the major industrial centers situated in Assam such as Coal India Limited (Ledo,
    Margherita), Brahmaputra Gas Cracker & Polymer Limited (Lepetkata, Dibrugarh), Cement Corporation of India Limited
    (Bokajan), Hindustan Paper Corporation Limited (Panchgram & Jagiroad), Assam Petrochemicals Limited (Namrup) etc.
    and serving the people of Assam with a consumer base of more than 64 lakhs and this is growing year by year.   </br>   </br>

    <h4> <strong>Location:</strong>  </h4> 
    Assam Power Distribution Company Limited  </br>
    Bijulee Bhawan     </br> 
    Paltanbazar        </br>
    Guwahati - 781001        </br>
    Assam - India         </br>
    
    {% endblock body %}

templates/city_dropdown_list_options.html
<option value="">---------</option>
{% for division in divisions %}
<option value="{{ division.pk }}">{{ division.name }}</option>
{% endfor %}

templates/common.html
<!DOCTYPE html>
<html>

<head>
  <title> {% block title %} APDCL {% endblock title %} </title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
    crossorigin="anonymous"></script>

</head>

<body>
  <nav class="navbar navbar-expand-lg p-3 bg-secondary shadow-lg">
    <div class="container-fluid">
      <a class="navbar-brand" href="index.html">
          <img src="static/img/1.png" alt="..." height="35" width="40"> <b>APDCL</b> 
      </a>

      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link"  href="index.html" aria-current="page" target="_self"> Home </a>
          </li>

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="/connections" role="button" data-bs-toggle="dropdown"
              aria-expanded="false">
              Connections
            </a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="#"></a></li>
              <li><a class="dropdown-item" href="/form">Add Connections</a></li>
              <li>
                <hr class="dropdown-divider">
              </li>
              <li><a class="dropdown-item" href="connection">Search Connections</a></li>
            </ul>
          <li class="nav-item">
            <a class="nav-link" href="/contact">Contact</a>
          </li>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/about">About Us</a>
          </li>
        </ul>
            <div class="collapse navbar-collapse justify-content-end" id="my-navbar">
                <ul class="navbar-nav">
                  {% if request.user.is_authenticated %}
                    {% csrf_token %}
                      <div class="nav-vl"></div>
                      <li class="nav-item">
                          <a class="nav-link" href="/logout">
                              <i class="fas fa-sign-out-alt"></i>Logout
                          </a>
                      </li>
                    {% else %}
                      <div class="nav-vl"></div>
                      <li class="nav-item">
                          <a class="nav-link" href="/login">
                              <i class="fas fa-sign-in-alt"></i>Login
                          </a>
                      </li>     
                    {% endif %}
                </ul>
            </div>
      </div>
    </div>
  </nav>

  {% if messages %}
  {% for message in messages %}
  <div class="alert alert-{{message.tags}} alert-dismissible fade show my-0" role="alert">
    <strong>{{message}} </strong>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
  {% endfor %}
  {% endif %}

  {% block body %}{% endblock body %}

    <footer>
      <div class="copyright">
        <br />
        <span> <strong><b> © 2023 Summer internship APDCL, GUIST </b> </strong> </span>
      </div>
    </footer>

    
</body>

</html>

<style>
  .copyright {
    font-size: 16px;
    text-align: center;   
    bottom: 0px; 
    width: 100%;
    position: fixed;
  }
</style>

templates/contact.html
{% extends 'common.html' %}

{% block title %}
Contact page
{% endblock title %}

{% block body %}

<style>
    .breadcrumb 
    {
      background-color: #f2f2f2;
      padding: 10px;
      border-radius: 5px;
    }
</style>

<nav aria-label="breadcrumb">
    <ol class="breadcrumb py-2">
        <li class="breadcrumb-item">
            <a href="index.html">Home</a>
        </li>
        <li class="breadcrumb-item active" aria-current="page">
            Contact Us
        </li>
    </ol>
</nav>

<div class="container-fluid px-0 mb-3">
    <h2 class="text-center">Contact Us </h2>

    <form method="post" action="/contact">
        {% csrf_token %}
        <div class="container ">
            <div class="mb-3">
                <label for="name" class="form-label">Name</label>
                <input type="text" class="form-control" id="name" name="name" placeholder="Name">
            </div>
            <div class="mb-3">
                <label for="email" class="form-label">Email address</label>
                <input type="email" class="form-control" id="email" name="email" placeholder="name@example.com">
            </div>
            <div class="mb-3">
                <label for="phone" class="form-label">Phone Number</label>
                <input type="phone" class="form-control" id="phone" name="phone" placeholder="Phone No.">
            </div>
            <div class="mb-3">
                <label for="issue" class="form-label">Complaint/Query</label>
                <textarea class="form-control" id="issue"  name="issue" rows="3"></textarea>
            </div>
            <button class="btn btn-primary" type="submit">Submit</button>
        </div>
    </form>
    
</div>
{% endblock body %} 

templates/form.html
{% extends 'common.html' %}

{% block title %}
Connection page
{% endblock title %}

{% block body %}

<div class="alert alert-success alert-dismissible fade show" role="alert">
    <strong>
      Documents required for new connection!
    </strong> </br>
    1. Latest Passport Size Photo of the Applicant (in jpeg or png format) </br>
    2. Proof of Identity (Voter identity card / Passport / Driving license / Ration card/ BPL card/ PAN card / Aadhaar Card) </br>
    3. Residential Address Proof (Driving License/ Bank Passbook/ Aadhaar Card / Telephone Bill / BPL Card / Passport)  </br>
    4. Proof of the legal occupation of the premises(Holding No., Lease Agreement, Rent Agreement, Sale Deed) </br>
    5. Test report from authorized electrical contractor / supervisor. </br>
    Note: Copies of all the documents uploaded shall be self-attested by the applicant and the original copy may be
    required to be produced at the time of inspection, if required by the licensee.
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
  
  <style>
    .breadcrumb {
      background-color: #f2f2f2;
      padding: 10px;
      border-radius: 5px;
    }
  </style>
  
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb py-2">
      <li class="breadcrumb-item">
        <a href="index.html">Home</a>
      </li>
      <li class="breadcrumb-item active" aria-current="page">
        New Connection
      </li>
    </ol>
  </nav>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
  <link href="static/css/connection.css" rel="stylesheet" />


  <h2>Consumer Form</h2>

  <form method="post" id="personForm" data-divisions-url="{% url 'ajax_load_division' %}" data-subdivisions-url= "{% url 'ajax_load_subdivision' %}">
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="Submit">
  </form>
  
  <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
  <script>
      $("#id_zone").change(function () {
          const url = $("#personForm").attr("data-divisions-url");  // get the url of the `load_cities` view
          const zoneId = $(this).val();  // get the selected zone ID from the HTML input
  
          $.ajax({                       // initialize an AJAX request
              url: url,                    // set the url of the request (= /persons/ajax/load-cities/ )
              data: {
                  'zone_id': zoneId       // add the zone id to the GET parameters
              },
              success: function (data) {   // `data` is the return of the `load_cities` view function
                  $("#id_division").html(data);  // replace the contents of the division input with the data that came from the server
                  /*
  
                  let html_data = '<option value="">---------</option>';
                  data.forEach(function (division) {
                      html_data += `<option value="${division.id}">${division.name}</option>`
                  });
                  console.log(html_data);
                  $("#id_division").html(html_data);
  
                  */
              }
          });
      });
  
      $("#id_division").change(function () {
              const url = $("#personForm").attr("data-subdivisions-url");  // get the url of the `load_cities` view
              const divisionId = $(this).val();  // get the selected zone ID from the HTML input
      
              $.ajax({                       // initialize an AJAX request
                  url: url,                    // set the url of the request (= /persons/ajax/load-cities/ )
                  data: {
                      'division_id': divisionId       // add the zone id to the GET parameters
                  },
                  success: function (data) {   // `data` is the return of the `load_cities` view function
                      $("#id_subdivision").html(data);  // replace the contents of the division input with the data that came from the server
                      /*
      
                      let html_data = '<option value="">---------</option>';
                      data.forEach(function (division) {
                          html_data += `<option value="${division.id}">${division.name}</option>`
                      });
                      console.log(html_data);
                      $("#id_division").html(html_data);
      
                      */
                  }
              });
      });
  </script>

{% endblock body %}

templates/home.html
{% extends 'common.html' %}

{% block title %}
Connection page
{% endblock title %}

{% block body %}

<div class="alert alert-success alert-dismissible fade show" role="alert">
    <strong>
      Documents required for new connection!
    </strong> </br>
    1. Latest Passport Size Photo of the Applicant (in jpeg or png format) </br>
    2. Proof of Identity (Voter identity card / Passport / Driving license / Ration card/ BPL card/ PAN card / Aadhaar
    Card) </br>
    3. Residential Address Proof (Driving License/ Bank Passbook/ Aadhaar Card / Telephone Bill / BPL Card / Passport)
    4. Proof of the legal occupation of the premises(Holding No., Lease Agreement, Rent Agreement, Sale Deed) </br>
    5. Test report from authorized electrical contractor / supervisor. </br>
    Note: Copies of all the documents uploaded shall be self-attested by the applicant and the original copy may be
    required to be produced at the time of inspection, if required by the licensee.
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
  
  <style>
    .breadcrumb {
      background-color: #f2f2f2;
      padding: 10px;
      border-radius: 5px;
    }
  </style>
  
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb py-2">
      <li class="breadcrumb-item">
        <a href="index.html">Home</a>
      </li>
      <li class="breadcrumb-item active" aria-current="page">
        New Connection
      </li>
    </ol>
  </nav>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
  <link href="static/css/connection.css" rel="stylesheet" />


  <h2>Consumer Form</h2>

  <form method="post" id="personForm" data-divisions-url="{% url 'ajax_load_division' %}" data-subdivisions-url= "{% url 'ajax_load_subdivision' %}">
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="Submit">
  </form>
  
  <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
  <script>
      $("#id_zone").change(function () {
          const url = $("#personForm").attr("data-divisions-url");  // get the url of the `load_cities` view
          const zoneId = $(this).val();  // get the selected zone ID from the HTML input
  
          $.ajax({                       // initialize an AJAX request
              url: url,                    // set the url of the request (= /persons/ajax/load-cities/ )
              data: {
                  'zone_id': zoneId       // add the zone id to the GET parameters
              },
              success: function (data) {   // `data` is the return of the `load_cities` view function
                  $("#id_division").html(data);  // replace the contents of the division input with the data that came from the server
                  /*
  
                  let html_data = '<option value="">---------</option>';
                  data.forEach(function (division) {
                      html_data += `<option value="${division.id}">${division.name}</option>`
                  });
                  console.log(html_data);
                  $("#id_division").html(html_data);
  
                  */
              }
          });
      });
  
      $("#id_division").change(function () {
              const url = $("#personForm").attr("data-subdivisions-url");  // get the url of the `load_cities` view
              const divisionId = $(this).val();  // get the selected zone ID from the HTML input
      
              $.ajax({                       // initialize an AJAX request
                  url: url,                    // set the url of the request (= /persons/ajax/load-cities/ )
                  data: {
                      'division_id': divisionId       // add the zone id to the GET parameters
                  },
                  success: function (data) {   // `data` is the return of the `load_cities` view function
                      $("#id_subdivision").html(data);  // replace the contents of the division input with the data that came from the server
                      /*
      
                      let html_data = '<option value="">---------</option>';
                      data.forEach(function (division) {
                          html_data += `<option value="${division.id}">${division.name}</option>`
                      });
                      console.log(html_data);
                      $("#id_division").html(html_data);
      
                      */
                  }
              });
      });
  </script>

{% endblock body %}

templates/index.html
{% extends 'common.html' %}

{% block title %}
Home page
{% endblock title %}

{% block body %}

<style>
    .mar {
        color : red; 
        height : 100%;
        width : 100%;
    }
</style>

<marquee behavior="scroll" class="mar" direction="left">
    <b>
        Stay alert and safe!
    </b>
</marquee>

<div class="col-xl-12 text-center">
  {% if user.is_authenticated %}
    <h2><b>Welcome, {{ user.username }} to the best website in the world!!!</b></h2>
  {% else %}
    <h2><b>Welcome to the best website in the world!!!</b></h2>
  {% endif %}
</div>

{% endblock body %}

templates/login.html
{% extends 'common.html' %}

{% block title %}
Login page
{% endblock title %}

{% block body %}


<link href="static/css/login.css" rel="stylesheet" />
{% for message in messages.get %}
<h5 class="cd">{{ message }}</h5>
{% endfor %}

    <div class="ab">
        <section class="wrapper">   
            <div class="form signup">
            <div class="main">
                <div class="logo">
                  <img
                    src="https://play-lh.googleusercontent.com/zNCkWerOvcmjkk6AKpuy0oJO4szR2G_CgEKgNSw0wm6LPkzTgfhiW3e6slJr00UV9Q"
                    height="100" width="100">
                </div>
            </header>
                <h1>Login</h1>
                <form method="POST" action="/login">
                    {% csrf_token %}
                    <div class="input-box">
                        <input type="username" id="username" name="username" placeholder="Username" required />
                    </div>
                    <div class="input-box">
                        <input type="password" id="password" name="password" placeholder="Password" required>
                    </div>
                    <div class="remember-forgot">
                        <label><input type="checkbox">Remember me</label>
                        <a href="#">Forgot Password?</a>
                    </div>

                    <button type="submit" class="btn">Login</button>

                    <div class="register-link">
                        <p>Don't have an account? <a href="/register">Register</a></p>
                    </div>
                </form>
            </div>
        </div>


{% endblock body %}

templates/register.html
{% extends 'common.html' %}

{% block title %}
Signup page
{% endblock title %}

{% block body %}

<link href="static/css/register.css" rel="stylesheet" />
{% for message in messages.get %}
<h5 class="cd">{{ message }}</h5>
{% endfor %}


<div class="ab">
<section class="wrapper">
  <div class="form signup">
    <header>
      <div class="main">
        <div class="logo">
          <img
            src="https://play-lh.googleusercontent.com/zNCkWerOvcmjkk6AKpuy0oJO4szR2G_CgEKgNSw0wm6LPkzTgfhiW3e6slJr00UV9Q"
            height="100" width="100">
        </div>
        Signup
      </div>

    </header>
    <form method="POST" action="/register">
      {% csrf_token %}
      <input type="username" id="username" name="username" placeholder="Username" required />
      <input type="text" id="email" name="email" placeholder="Email address" required />
      <input type="password" id="password1" name="password1" placeholder="Password" required />
      <input type="password" id="password2" name="password2" placeholder="Password" required />
      <div class="checkbox">
        <input type="checkbox" id="signupCheck" />
        <label for="signupCheck">I accept all terms & conditions</label>
      </div>
      <input type="submit" value="Signup" />
    </form>
  </div>

{% endblock body %}

templates/subdivision_dropdown_list_options.html
<option value="">---------</option>
{% for subdivision in subdivisions %}
<option value="{{ subdivision.pk }}">{{ subdivision.name }}</option>
{% endfor %}